# Meta
description: A minimal hexo theme.
keywords: hexo,theme,typescript
site_desc: Write Everything.

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: About
  slug: about
  url: /about
- name: Archives
  slug: archives
  url: /archives

# Search
search: 
  enable: true
  service: google # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics:
favicon: /favicon.png
author_url: http://xinoassassin.com

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: mailto:phnjs211@gmail.com
- slug: github
  url: https://github.com/xinoassassin
- slug: twitter
  url: https://twitter.com/xinoassassin
- slug: sina-weibo
  url: http://weibo.com/XiDeAssassin
- slug: rss
  url: /atom.xml

